### ISSUE TITLE
MultiQML wont run

### ISSUE THREAD

**Issue by Blackbirdag** [nextgis/MultiQML#9]
this plugin will not run for me. I have uninstalled it and the whole QGIS program and still have the same problem, another colleague is using it without problem... any suggestions

**Comment by simgislab** [comment]
won't run how? does it produce an error message?

**Comment by Blackbirdag** [comment]
Nothing at all... No message no screen nothing in running processes.   No visible response



Julie Robinson

Blackbird | 250-262-7576 | julie@blackbird.ca


-------- Original message --------

**Comment by simgislab** [comment]
can you please provide:
* version of QGIS
* version and type of OS
* concrete series of steps you do (do you just open MultiQML window? or something else)

thanks

**Comment by Blackbirdag** [comment]
Ok so foolishly, after 2 weeks today we connected to another screen and there is the tool on the second screen sorry for the hassle.  It was a display issue.



Julie Robinson

Blackbird | 250-262-7576 | julie@blackbird.ca


-------- Original message --------

**Comment by simgislab** [comment]
glad it worked. Closing.
